function [scenario, egoVehicle] = AEB_CCRb_2_initialGap_12m()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.13 (R2022b) and Automated Driving Toolbox 3.6 (R2022b).
% Generated on: 15-Aug-2023 16:41:01

% Construct a drivingScenario object.
scenario = drivingScenario('StopTime', 5.85);

% Add all road segments
roadCenters = [0 0 0;
    1000 0 0];
roadWidth = 10;
road(scenario, roadCenters, roadWidth, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [20 0 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Vehicle UnderTest');
waypoints = [20 0 0;
    150 0 0];
speed = 13.89;
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
globalVehicleTarget = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [36.7 0 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Global Vehicle Target');
waypoints = [36.7 0 0;
    70 0 0;
    118.23 0 0];
speed = [13.89;13.89;0];
trajectory(globalVehicleTarget, waypoints, speed);

